### ISSUE TITLE
Fix cookieManager layout

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-gdpr-plugin#10]
![image](https://user-images.githubusercontent.com/8600029/41579030-6c6eb586-7395-11e8-8487-5af515a1486c.png)

* [X] Make all settings `off` by default (except session cookie) (daa9258)
* [x] Add option to choose the lifetime duration of the `gdpr_cookie_consent` cookie
* [x] Add an option to not include the default JS code
* [X] Use `html_clean` for HTML outputs (d4fff52)

via https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/issues/8

**Comment by ayumihamsaki** [comment]
> Add option to choose the lifetime duration of the gdpr_cookie_consent cookie

The law states cannot set something forever, Google uses these settings (we could copy them):

- 3 months
- 6 months
- 12 months (1 year)
- 24 months (2 years)
- 36 months (3 years)

~ I think you can't do longer than 3 years...?
