### ISSUE TITLE
choosing decline turns all toggles to "enabled"

### ISSUE THREAD

**Issue by CptMeatball** [OFFLINE-GmbH/oc-gdpr-plugin#14]
**What should happen**
When choosing`decline` on the cookiebanner, and navigating to the cookiemanager, all toggles except the required are turned `off`. 

**What actually happens**
When choosing`decline` on the cookiebanner, and navigating to the cookiemanager, all toggles except the required are turned `on`.

**Comment by tobias-kuendig** [comment]
Thanks for the heads up! This is fixed in 752965c / 1.0.17
