### ISSUE TITLE
Update Cookie Group Section to add Preloaded List

### ISSUE THREAD

**Issue by ayumihamsaki** [OFFLINE-GmbH/oc-gdpr-plugin#20]
~Just to let you know I am currently working on a list for:

`Cookie Groups > Form > Purpose`

Should be done this week.  Looks like this so far:

![untitled](https://user-images.githubusercontent.com/17784082/41622476-974a6daa-7407-11e8-8408-76ad990aa3b4.png)

Thinking of updating the Cookie Group screen to this, when I finish putting together the list of Purpose Desciptions for a bunch of cookies, see screenshot of idea:

![untitled](https://user-images.githubusercontent.com/17784082/41662683-8fe493c8-7499-11e8-9e76-dcb48535bde1.png)

Will finish the list of in few days time, I think easy to custom code a form partial for this (The Previewer bit).

**Comment by tobias-kuendig** [comment]
Maybe reuse the same textarea for the preview and the custom description?

> Select description preset

If the users selects a present and the textarea is empty just fill in the preset. If the user does not select a preset she can enter a custom description.

This could be done all "October-native" using `depends_on`.

**Comment by ayumihamsaki** [comment]
Ok sounds good, wonder idea!

**Comment by ayumihamsaki** [comment]
I do a list for this purpose as well,..

![untitled2](https://user-images.githubusercontent.com/17784082/41664316-5da1ffb4-749d-11e8-8f5b-901c78d237da.png)

**Comment by ayumihamsaki** [comment]
Going to close this issue and open up two separate ones to make tracking easier!
