### ISSUE TITLE
Initial Status field still present in fieldlist

### ISSUE THREAD

**Issue by CptMeatball** [OFFLINE-GmbH/oc-gdpr-plugin#22]
Since 1.1, the `initial status` of a cookie is removed. However, the field is still present in the fields.yaml (https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/blob/develop/models/cookie/fields.yaml#L15).

**Comment by tobias-kuendig** [comment]
The field is okay but there's a bug in the migration file. It should remove the column from the `cookie_groups` table, not the `cookies` table.

The `initial_status` was only removed from the groups.

**Comment by tobias-kuendig** [comment]
This has been corrected in ded31ef. Thanks for bringing this to our attention!
