### ISSUE TITLE
Add "Dismiss/Show" Feature

### ISSUE THREAD

**Issue by ayumihamsaki** [OFFLINE-GmbH/oc-gdpr-plugin#23]
The Law states that the banner should have the following features:

- Accept
- Reject
- Dismiss
- Show

### Accept

When the user clicks on the button "Accept" they are **ticking** all the options in the advanced setting page.

### Reject

When the user clicks on the button "Reject" they are **un-ticking** all the options in the advanced setting page.

### Dismiss

The user does not have to decide straight away! They can decide at any time they choose. This would be simply a **close button** on the banner to hide it.

### Show

The user does not have to decide straight away! They can decide at any time they choose. This would be simply a **show button** on the banner to display it. **OR THE WEBMASTER COULD CREATE A LINK IN THE FOOTER FOR EXAMPLE TO THE ADVANCED SETTINGS WEBPAGE.**

### Example with the current Banner Design

![41365745-803f0ce6-6f3a-11e8-93ff-7dc0f683e241](https://user-images.githubusercontent.com/17784082/41720793-10370106-755c-11e8-9c19-40d6191873b6.png)

### Show as a Button or Footer Link

You could do one of three possible things for the Show, either create a button in the bottom of the screen in the bottom left or right hand corners. Or create a footer link (which would be the best method).

Example of the three methods: (I think footer method is best option)

![aaa](https://user-images.githubusercontent.com/17784082/41726139-6c29b2a8-7569-11e8-9df3-eac4debf8b75.png)

**_Note: The Footer link is the best method and should be mentioned in the updated doc's_**

**Comment by ayumihamsaki** [comment]
## Consent by LAW

Also following on from the above and reading the READ.ME page, maybe it's my misunderstanding but I strongly feel this section is wrong and not needed, see screenshot:

![untitled](https://user-images.githubusercontent.com/17784082/41760878-612a7e80-75ed-11e8-8f44-1b524deccbfd.png)

### An example which does not pass the law

1. A user goes to the first webpage and sees the Banner.
2. A user does NOT select a "Consent Option" from the banner and goes to the second webpage.
3. The second webpage does not show the Banner.

### An example which does pass the law

1. A user goes to the first webpage and sees the Banner.
2. A user DOES select a "Consent Option" from the banner and goes to the second webpage.
3. The second webpage does not show the Banner.

### The LAW

The Banner MUST show on every webpage until the user selects one of the following "Consent Options" these being: `Accept`, `Reject` or `Dismiss`. Or they click on the "Advanced Settings" link and `Save the Options there`.

Therefore I think this is not needed: https://github.com/OFFLINE-GmbH/oc-gdpr-plugin#ignore-behaviour

**Comment by CptMeatball** [comment]
Agree with the dismiss option! 

About the ignore behaviour; 
I think more people should comment on this, as the gdpr is one of the most misunderstood laws in terms of what is and what is not allowed. So more people should cast a vote about it and see what is necessary.

**Comment by ayumihamsaki** [comment]
@tobias-kuendig Please can you, finish off the PHP Code. The "onDismiss" function and "onShow" function(s) needs to be coded (for users to add a button to re-show the banner and/or hide the banner). I started it and wrote the ccs code and the component code - just not the php functions as I thought best for you to do that.
