### ISSUE TITLE
Upgrade the php files to php7 strict standard

### ISSUE THREAD

**Issue by ayumihamsaki** [OFFLINE-GmbH/oc-gdpr-plugin#24]
Minor request feature, but this is something I do with all my plugins and think it should be added to yours.

`declare(strict_types=1);`

Add the following to the **_top_** of all the php files.

So for example `Plugin.php` file would be:

```
<?php 

declare(strict_types=1);

namespace OFFLINE\GDPR;

use Backend\Facades\Backend;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Session;
use OFFLINE\GDPR\Classes\Cookies\ConsentCookie;
use OFFLINE\GDPR\Components\ConsentManager;
use OFFLINE\GDPR\Components\CookieBanner;
use OFFLINE\GDPR\Components\CookieManager;
use OFFLINE\GDPR\Console\CleanUp;
use OFFLINE\GDPR\Models\CookieConsentSettings;
use OFFLINE\GDPR\Models\DataRetentionSettings;
use System\Classes\PluginBase;

class Plugin extends PluginBase
{
..
```

I can go through all the files and add that for you if you like.

**Comment by tobias-kuendig** [comment]
I don't see a real benefit if we don't also add scalar type hints to all method declarations?
