### ISSUE TITLE
Re-Code The CSS for The Banner and Cookie Manager

### ISSUE THREAD

**Issue by ayumihamsaki** [OFFLINE-GmbH/oc-gdpr-plugin#26]
Gonna do a Pull Request to update the CSS to work on all Browsers with the added prefix and also create min files to add to the updated doc's at a later date.

**Comment by CptMeatball** [comment]
Might also be a good idea tot look at general styling of the elements. 

There's a min-height on the cookiesmanager for example that's not really necessary I think.

**Comment by ayumihamsaki** [comment]
CSS on Banner won't pass basic Web Accessibility standards! Gonna have to throw it in the bin and re-code it properly!

**Comment by ayumihamsaki** [comment]
@CptMeatball I will check that as well. Probably lots of issues there as well.

**Comment by ayumihamsaki** [comment]
Example on Mobile Device:

![untitled](https://user-images.githubusercontent.com/17784082/41884195-38bd3492-78ea-11e8-9581-3c304cf76e44.png)

(Best to throw in bin and do it correctly!!!

**Comment by tobias-kuendig** [comment]
> Best to throw in bin and do it correctly!!!

Thank you for these kind words.

Did you add the viewport meta-tag?

    <meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by ayumihamsaki** [comment]
@tobias-kuendig Hi, sorry for my words and yes I did use the viewport tag. But the current CSS will completely fail if you throw it into Lighthouse for example, I strongly do not recommend anyone use the current css and I will do a major update to it today and correct all the errors! That is why I say throw it in bin, as I recommend users to use a coming new version of css that will correct all the errors.

~Anyway leave it with me I will work on this today.

**Comment by ayumihamsaki** [comment]
New vs Old Design:

![mobile](https://user-images.githubusercontent.com/17784082/41924452-fab75e20-7961-11e8-8438-befef1d12ca6.png)

**Comment by CptMeatball** [comment]
I actually prefer the left one. Also, design is something that probably is different across websites. 

The gradient buttons on the new design are not really in sync with the current design trends and I'm also not that fond of the yellow.

The old design seems a bit a cleaner.

**Comment by tobias-kuendig** [comment]
Thank you @ayumihamsaki for updating the CSS.

I will remove the gradients and clean up the design a bit. I tried to keep the design as simple as possible and make it easy for the enduser to adjust it to the site's design. 

Using solid background colors removes the need for vendor prefixes. I don't know what versions of browsers you were targeting but I may also remove some other vendor prefixes like box-shadow and transition since theses properties had good browser support for many month now.

**Comment by ayumihamsaki** [comment]
@CptMeatball @tobias-kuendig Thanks guys for extra input.

> Using solid background colors removes the need for vendor prefixes. I don't know what versions of browsers you were targeting but I may also remove some other vendor prefixes like box-shadow and transition since theses properties had good browser support for many month now.

They are there for OLD Browser support. But up to you if you want to remove them. Just make sure webmasters have all the right Polyfills in place.

Some extra notes for some of my changes (for future reference):

- One on left won't pass Mobile Standards as Font Text has to be 16px or greater see here: https://github.com/GoogleChrome/lighthouse/issues/3174

- Another issue was that the old CSS gave a Google Mobile Interstitial Penalty between 320 - 380 px. Because the Banner size became way to high, see screenshot:

 ![untitled](https://user-images.githubusercontent.com/17784082/41978377-a1763418-7a19-11e8-802a-dea56cdd9306.png)

- Responsive errors on some screen sizes.

- Also bad touch-points on mobile devices, as on certain device sizes the distance of click/touch points was too close.

- Added Accessibility WAI-ARIA and correct rel-tags and other Web Standards Accessibility factors.

- Corrected contrast levels to pass WCAG 2 AA Spec.

- Added hover effects, also removed the bad focus ring that the old css had.

- Added the Dismiss button. Also made sure the text and other buttons have correct distance on re-size over the dismiss button for tap distances.

Many other CSS things.

**Comment by ayumihamsaki** [comment]
@tobias-kuendig Just tested the CSS you configed and wouldn't pass many Web Standards listed above!!!
