### ISSUE TITLE
Permission to Expand your Plugin - Info and Help Section

### ISSUE THREAD

**Issue by ayumihamsaki** [OFFLINE-GmbH/oc-gdpr-plugin#28]
Hi,

If you would allow me to expand your plugin and add a "Info and Help" Section, the new menu tabs would look like this:

![41735643-1bfc1a82-7582-11e8-9fc5-2deed6df84da](https://user-images.githubusercontent.com/17784082/41780877-e30cf2f8-762d-11e8-9c95-4bf9c5ecae9f.png)

It would link to a webpage location of: `/offline/gdpr/info` from there it would link to several webpages giving the following infomation.

An example of a bare bones content for the `/offline/gdpr/info` webpage will be the following screenshot:

![untitled](https://user-images.githubusercontent.com/17784082/41781704-23ef3d7e-7630-11e8-896e-626c01adfdb0.png)

Then I can go in to greater detail with the following Table of Contents Section and gives the users a full set of infomation on the Law, How to Use the Plugin and how best to set up things etc.

The webpages will use HTML, PRISMJS for the Coding and will be able to switch to other langues such as French and German etc. (Won't be using Markup as I use lots of new HTML5 semantics).

This will then allow to add extra infomation in the future if other new sections get added to the plugin.

Any other content ideas, or suggestions are welcome.

This links on to the two issues found: [11](https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/issues/11) and [12](https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/issues/12).

Let me know if it's ok and I will be happy to create the whole section for you.

(I decided to write this issue and show you what I am thinking right now, so you can understand my suggestions I have made for the plugin to pass GDPR and ePrivacy).

**Comment by ayumihamsaki** [comment]
@tobias-kuendig Thanks.

**Comment by tobias-kuendig** [comment]
This was a huge addition! Looking great, thank you @ayumihamsaki.

**Comment by ayumihamsaki** [comment]
Welcome.

**Comment by tobias-kuendig** [comment]
I refactored the info section and removed all the unneccessary models and controller actions. Please make sure to bring your forks up to date.
