### ISSUE TITLE
Tiny Error - Connect up the 2nd repeater field

### ISSUE THREAD

**Issue by ayumihamsaki** [OFFLINE-GmbH/oc-gdpr-plugin#29]
See Pull Requests:

https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/pull/27/commits/acccfcaed4ca8d5f56a1ff4234fa0ca75efcf9f2

https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/pull/27/commits/a38293aab73d6aad6b46e83e1613d9e309f15989

https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/pull/27/commits/d47519843e5f688b9e5617843afcd212cdbc10f5

**Comment by tobias-kuendig** [comment]
This has been fixed in #27
