### ISSUE TITLE
Apps default state always false

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-gdpr-plugin#3]
Hi,  

Applications default state is always set to false even if you set it to true in plugin settings.

In app.js component's partial, line 5 :  
````
            default: {{ app.default ? 'true' : 'false' }},
````
must become 
````
            default: {{ app.application_state ? 'true' : 'false' }},
````

Thank's for plugin ! 👍

**Comment by tobias-kuendig** [comment]
Good catch! Fixed in 1c8783e.
