### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'level_provider' in 'field list'

### ISSUE THREAD

**Issue by ayumihamsaki** [OFFLINE-GmbH/oc-gdpr-plugin#31]
Done a fresh install and the following error shows:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'level_provider' in 'field list' (SQL: insert into `offline_gdpr_cookies`

Screenshot below:

![untitled](https://user-images.githubusercontent.com/17784082/41850550-decf2b24-787c-11e8-95b5-6cab744364b6.png)

~Also "components" probably need updating to connect everything up!

**Comment by tobias-kuendig** [comment]
This is fixed via e81c4ec.

The components will be reworked in #11 and #10
