### ISSUE TITLE
Question - missing translations Klaro! Consent Manager 

### ISSUE THREAD

**Issue by Hessel91** [OFFLINE-GmbH/oc-gdpr-plugin#35]
![image](https://user-images.githubusercontent.com/7326568/41876870-9a272ba4-78cf-11e8-8ef9-206152c78144.png)

I know how to translate the describtion etc in the translations tab however i can't figure out where to translate the title, button name etc.

**Comment by tobias-kuendig** [comment]
You can add custom translations via the backend settings page. 

https://github.com/OFFLINE-GmbH/oc-gdpr-plugin#translations

Add your JSON string as shown in this image:

![image](https://user-images.githubusercontent.com/8600029/41891351-35318e70-7914-11e8-802c-8c8fbc2b58ee.png)

You may also consider to submit a PR to the Klaro! project to get NL translations out-of-the-box:

https://github.com/KIProtect/klaro/tree/master/src/translations

**Comment by tobias-kuendig** [comment]
Closed due to inactivity.
