### ISSUE TITLE
banner buttons dont seem to work

### ISSUE THREAD

**Issue by michalise** [OFFLINE-GmbH/oc-gdpr-plugin#44]
i setup some cookies with different manage levels, i went and tested the banner on clicking the decline button it seemed to do nothing, i was expecting it to set all the cookie levels to zero, likewise with the accept button i was expecting it to select all the cookie levels to the max levels but it also seemed to not do anything to the cookies in the manager screen?

**Comment by tobias-kuendig** [comment]
What version of the plugin are you running?

**Comment by michalise** [comment]
v1.3.2

**Comment by michalise** [comment]
ok, I will go back to old version, i hope you can fix this issue

**Comment by tobias-kuendig** [comment]
Did you include the framework extras? I am unable to reproduce the issue. The only thing I can think of is that the framework extras were missing and therefore the AJAX requests to the backend didn't happen.

**Comment by tobias-kuendig** [comment]
We've just released version 2.0 of the plugin. Please try again with this stable version.

**Comment by michalise** [comment]
hello thank you for your hard work updating to v2, i installed and updated to v2 and tested it and same problem, i will explain in detail my testing. i created a cookie group and then added some cookies, the first cookie has 2 levels, the second cookie has 3 levels and the third cookie has 5 levels. when i click on the banner decline button i was expecting to see the three cookies in the manager to show the slider at position zero, but no change is observed. when i delete the cookie and re-run the test and click on the accept button, i expect to see the cookies in the manager showing the slider positions, cookie 1 at level 2, cookie 2 at level 3 and cookie 3 at level 5, but again the banner button accpet does not change the cookie values in the manager, also yes i have the famework extras and scripts placed on the same page, the banner does display so i know the ajax is working after i press the buttons, but it does not seem like the banner is connected up to the cookie manager somehow?

**Comment by michalise** [comment]
here is a video showing the issue on your demo website: https://youtu.be/sQAl0vkbwIs

**Comment by tobias-kuendig** [comment]
Thank you for going the extra mile and recording the video.

The behaviour shown is actually what was configured on our demo page (default state for all cookies = disabled, default level = Extended Tracking)

I have updated the configuration on the demo page ‒ you should see it's working now.

Maybe your database schema got messed up when migrating between the plugin versions? Do you have a cookie level preselected? Is the inital status set to true for each cookie?

If it's nothing confidential you could upload a dump of your `offline_gdpr_cookies` and `offline_gdpr_cookie_groups` tables and I'll take a look and try to reproduce the error.

**Comment by michalise** [comment]
i had a look at your demo website and the accept button looks like it is working now, but when i clear all the cache and cookies, then i start again and click on the decline button on the banner and then check the settings, none of the levels are set at zero, see screenshot

![s](https://user-images.githubusercontent.com/41244231/43160556-6e96adc4-8f7d-11e8-8def-c6fce95f5fed.png)

if you can get both states working then i will try to copy your setup and see if i can fix it?

**Comment by tobias-kuendig** [comment]
This is intended behaviour:
The `Extreme tracking` in this example is set as default level, so it get preselected. Since the cookie itself is disabled it doesn't matter though.

Setting it to the lowest level wouldn't make any more sense since the lowest level doesn't necessarily mean no tracking. 

`gdprCookieAllowed` will return `false` in this case (even with the preselected "extreme" level). `gdprAllowedCookieLevel` will return `-1` (= cookie is disabed).

**Comment by tobias-kuendig** [comment]
The level selector is hidden for disabled cookies since version 2.0.2. This should clear things up.

**Comment by michalise** [comment]
thanks looks good now
