### ISSUE TITLE
Mass assignment

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-gdpr-plugin#46]
It would be fine if we could add default settings for groups and cookies, ,via [mass assignment](https://octobercms.com/docs/database/model#mass-assignment) in tools like [oc-bootstrapper](https://github.com/OFFLINE-GmbH/oc-bootstrapper) or seeder files.  

I only repeat, or almost repeat, the same parameters at each site. :-/

**Comment by tobias-kuendig** [comment]
Hi @damsfx 

This is definitely on our wishlist as well since we experience the same problem.

I like the idea to add this to oc-bootstrapper. Maybe I'll add a json export/import feature as well for everyone who wants to easily copy the settings between different projects.

**Comment by damsfx** [comment]
Temporarily would it not be possible to add a `protected $fillable` to the **Cookie** and **CookieGroup** models!?

**Comment by tobias-kuendig** [comment]
Sure! Please open a PR with the changes and I'll release it as a new version.
