### ISSUE TITLE
Translation in partials

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-gdpr-plugin#5]
Hi,

The new Cookie Manager component use different partials and specially a dedicated one for the submit button.  
That's great for translation but ... 

Why not use the "trans" filter for the default view !?
````
{{ 'offline.gdpr::lang.common.enabled' | trans }}

// give the word : Enabled (en), Aktiviert (de), Activé (fr)
````
It takes advantage of the provided translation's files, don't need specific partial for specific language (if lang file is present in the plugin).

ex: 
````
<button type="submit" class="gdpr-cookie-manager__submit-button">
    {{ 'offline.gdpr::lang.common.save_settings' | trans }}
</button>
````

**Comment by tobias-kuendig** [comment]
Good point! Fixed in 09bed29a24bd36408ad890427c0b84e953836334
