### ISSUE TITLE
Split language files in frontend and backend

### ISSUE THREAD

**Issue by CptMeatball** [OFFLINE-GmbH/oc-gdpr-plugin#50]
At the moment the frontend also uses the language file to load language dependent strings. As this language file is rather large it's not easy to create new languages for the front-end as you preferrably want to translate the entire file. This makes people hesitant to PR new translations.

Therefore I think it would be best to split the language files into frontend and backend, to speed up possible translations for the frontend. The backend does not need to be translated for every language, but the front-end should be translated into way more languages than the we have now.

**Comment by tobias-kuendig** [comment]
Great idea! What's your suggested solution for this? Can we create a `frontend.php` under `lang/xy/` to be included automatically? I have never used multiple language files before.

**Comment by CptMeatball** [comment]
Yes! Will PR something today ;)
