### ISSUE TITLE
Why the "hard_reload" is no longer available?

### ISSUE THREAD

**Issue by iboved** [OFFLINE-GmbH/oc-gdpr-plugin#54]
Why the "hard_reload" is no longer available? Why did you remove this option? This is a useful option.
[Here](https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/blob/develop/components/CookieBanner.php#L36-L41) you didn't remove this propery. And [here](https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/blob/develop/components/CookieBanner.php#L64) we have this option. But why did you delete the property declaration - `public $hardReload = false;` at the top of the CookieBanner class?
Thanks for the answer.

**Comment by tobias-kuendig** [comment]
Thanks for pointing out the dead code. The property simply wasn't removed completely by accident.

What's your use-case for the hard reload option? This offers nothing you cannot do with the soft reload option we currently provide. Also, the user experience suffers a lot when a hard reload is triggered.

**Comment by iboved** [comment]
@tobias-kuendig I have to move all my analytic codes in one partial if I use soft reload.
P.S. [Here](https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/blob/develop/components/cookiebanner/optin.htm#L8) and [here](https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/blob/develop/components/cookiebanner/optin.htm#L12) we also have mentions of the "hard_reload" property.

**Comment by tobias-kuendig** [comment]
Thanks, the code has been removed too.

You can always overwrite the `cookieBanner/optin.htm` partial and decide for yourself what to do in the `data-request-success` attribute. You could even send the `data-request` to an other component that you control yourself. Just make sure to [register the user's decision in the consent cookie](https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/blob/develop/components/CookieBanner.php#L97).
