### ISSUE TITLE
Unable to use Klaro

### ISSUE THREAD

**Issue by fmulassano** [OFFLINE-GmbH/oc-gdpr-plugin#58]
Following the guide i have installed and configured the GDPR plugin.
i see the consent bar but the klaro manager doesn't appear... in javascript console i have this error Uncaught SyntaxError: Unexpected end of input (index) : 467

![klaro_error](https://user-images.githubusercontent.com/18305442/56420209-65ded280-629d-11e9-9999-87a9f9940468.png)

**Comment by tobias-kuendig** [comment]
Could you post the whole `klaroConfig` variable from your website's source code? Would it be possible that you have a syntax error in the `translations` json you've entered in the backend?

**Comment by faselunare** [comment]
yes, this is the code

`

<script>
--
  | var klaroConfig = {
  | elementID: 'oc-gdpr-klaro',
  | cookieName: 'oc-gdpr-klaro',
  | cookieExpiresAfterDays: 30,
  | privacyPolicy: '/privacy',
  | default: false,
  | mustConsent: false,
  | lang: 'en',
  | translations: {
  | it: {
  | consentModal: {
  | description:
  | 'Here you can see and customize the information that we collect about you. Entries marked as "Example" are just for demonstration purposes and are not really used on this website.',
  | },
  | inlineTracker: {
  | description: 'Example of an inline tracking script',
  | },
  | externalTracker: {
  | description: 'Example of an external tracking script',
  | },
  | adsense: {
  | description: 'Displaying of advertisements (just an example)',
  | },
  | matomo: {
  | description: 'Collecting of visitor statistics',
  | },
  | camera: {
  | description:
  | 'A surveillance camera (just a silly example for an IMG tag)',
  | },
  | cloudflare: {
  | description: 'Protection against DDoS attacks',
  | },
  | intercom: {
  | description:
  | 'Chat widget & collecting of visitor statistics (just an example)',
  | },
  | mouseflow: {
  | description: 'Real-Time user analytics (just an example)',
  | },
  | googleFonts: {
  | description: 'Web fonts hosted by Google',
  | },
  | purposes: {
  | analytics: 'Analytics',
  | security: 'Security',
  | livechat: 'Livechat',
  | advertising: 'Advertising',
  | styling: 'Styling',
  | }
  | },
  | apps: [
  | ]}</script>

`

**Comment by tobias-kuendig** [comment]
Please check the translations object you have entered in the backend. You are missing a closing `}` in there (probably on the `purposes` key)

**Comment by faselunare** [comment]
Thanks, it works now
