### ISSUE TITLE
addToggleEvents, if levels are not defined

### ISSUE THREAD

**Issue by RonMen** [OFFLINE-GmbH/oc-gdpr-plugin#60]
Hi.

In '/components/cookiemanager/scripts.js' in function 'addToggleEvents' the levels can be empty, so setting 'levels.style.display = ...' will run into error.

I think it would be right to check if levels not undefined, so it should be eg.
``
levels && levels.forEach(function(level) {
  level.style.display = 'block';
});
``
and
``
levels && levels.forEach(function(level) {
  level.style.display = 'none';
});
``

Regards
RonMen

**Comment by tobias-kuendig** [comment]
Good catch, thank you! This is fixed in 404364d and released as v2.0.12
