### ISSUE TITLE
Menu item "cookies" appears then disappears

### ISSUE THREAD

**Issue by drmzio** [OFFLINE-GmbH/oc-gdpr-plugin#68]
Is this intentional? The cookies menu item only appears in the **Plugins & Updates** page of the backend.

**Settings page**
![image](https://user-images.githubusercontent.com/6914518/80738888-7b025a00-8aca-11ea-873a-6fae0dbaa28a.png)

**Other pages**
![image](https://user-images.githubusercontent.com/6914518/80738904-805fa480-8aca-11ea-8464-efd0cc9f11a0.png)

**Comment by tobias-kuendig** [comment]
That's strange. I cannot reproduce this issue. 

Are you on the latest version? Also, can you try disabling and re-enabling the "log cookie requests" option in GDPR's general settings and see if that helps?

According to the code, the menu item should be removed if the `log_enabled` setting is false:

https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/blob/develop/Plugin.php#L61
