### ISSUE TITLE
Issue?

### ISSUE THREAD

**Issue by eltso** [OFFLINE-GmbH/oc-gdpr-plugin#69]
OK, I installed plugin and followed your tutorial but ... I have few things that I can't seem to get to work.
First: Consent on the bottom of the screen - decline and accept buttons don't work, advanced settings do.
Second: On advanced settings page I choose that I allow analytics cookie, but page wont start tracking, code works cause if I put it in layout file, then tracking works.

I have been searching for few hours now and I'm really stuck, maybe You can help me.

Advanced setting page, I have made all cookies active and turned Start-up selector on, but still their not turned on by default.

**Comment by tobias-kuendig** [comment]
Have you included all the JS dependencies? (October's AJAX framework)
Do you see any errors in your JS console. Do you see any http requests being sent to the backend? Does the backend return your analytics code (see network tab in devtools) when you accept the cookie?

**Comment by eltso** [comment]
Ok, thanks for that AJAX framework info, that made buttons work.
I was certain I put partial on layout but It was not there, so after adding it I can enable analytics if user presses Accept.
But, still in cookies page, analytics cookie is not selected by default and if visitor clicks advanced settings from consent bar and does nothing on cookies page, then consent bar disappears and analytics cookie will not be enabled.
If I press Accept on consent bar and then go to cookies page, it shows that analytics cookie is enabled and analytics works.

**Comment by tobias-kuendig** [comment]
> But, still in cookies page, analytics cookie is not selected by default and if visitor clicks advanced settings from consent bar and does nothing on cookies page, then consent bar disappears and analytics cookie will not be enabled.

That's how GDPR specifies it. If you select "advanced settings" you want to configure what cookies are set, you don't give consent to set all the cookies.

Only the "accept" button will enable all default cookies. Every other action does nothing.

**Comment by eltso** [comment]
Ok, If thats how GDPR has to work then I have everything working, thanks for all the help :)
