### ISSUE TITLE
.remove unsupported on IE11

### ISSUE THREAD

**Issue by wordshop-git** [OFFLINE-GmbH/oc-gdpr-plugin#71]
The cookiebanner buttons are using .remove and on IE this isn't supported so you can't close/ accept the cookie banner

This issue maybe elsewhere in the plugin as well but we've only spotted it on the cookie banner

**Comment by Andi-Moser** [comment]
Hi,

We do not support IE11, however you can either overwrite the partials yourself or use this IE11 polyfill:

```javascript
    // Create Element.remove() function if not exist
    if (!('remove' in Element.prototype)) {
        Element.prototype.remove = function() {
            if (this.parentNode) {
                this.parentNode.removeChild(this);
            }
        };
    }
```

I hope this helps!
