### ISSUE TITLE
v2.2.11: Error when Translate plugin is not installed

### ISSUE THREAD

**Issue by guus-frenken** [OFFLINE-GmbH/oc-gdpr-plugin#81]
Commit https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/commit/8cee30901509f2c6caf9befe396b8cc61355a2a7 assumes that RainLab/Winter.Translate plugin is installed and will throw a "Class 'RainLab\Translate\Models\Attribute' not found" error when this is not the case.

**Comment by tobias-kuendig** [comment]
This is fixed in the latest release, thank you!
