### ISSUE TITLE
Throw error when Translate plugin enabled with 2 languages.

### ISSUE THREAD

**Issue by bachvtuan** [OFFLINE-GmbH/oc-gdpr-plugin#82]
Both plugins are up to date:
- Translate plugin version: 1.9.2
- OC-gdpr-plugin: 2.2.12
The error only thrown when edit "cookies and module" item.

![Screenshot from 2021-08-11 12-14-28](https://user-images.githubusercontent.com/2065400/128973430-e6b4966e-d516-4911-b67b-705ae71e1caf.png)

**Comment by bachvtuan** [comment]
I found out that plugin does not detect Translate Attribute class.

Current code 
```
 if (class_exists(RainLab\Translate\Models\Attribute::class)) 
```
Fix code and that works.
```
 if (class_exists(\RainLab\Translate\Models\Attribute::class)) 
```

**Comment by tobias-kuendig** [comment]
Good catch! Thank you very much. Fixed in https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/commit/33a44e4b7973c03b028353c44ee3cbf1bb096f38
