### ISSUE TITLE
Conflict with Vdlp.csrf plugin

### ISSUE THREAD

**Issue by mkinternet** [OFFLINE-GmbH/oc-gdpr-plugin#86]
Cookie manager component doest't work when Vdlp.csrf plugin is instaled. Cookie settings are not saving.

Replace line https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/blob/657ff7f5c5665193b87f8eaba0d68fe5ce88cc37/components/cookiemanager/default.htm#L1 with:

{{ form_open({'method':'post' }) }}

This will add nessesary token fields to the form https://octobercms.com/docs/services/html#form-tokens

**Comment by tobias-kuendig** [comment]
Very good suggestion, thank you! Added in release v2.2.14
