### ISSUE TITLE
Too short DB field 'useragent'

### ISSUE THREAD

**Issue by webBook-cz** [OFFLINE-GmbH/oc-gdpr-plugin#89]
![image](https://user-images.githubusercontent.com/14330711/163003152-c3961aae-f29d-4da7-84f8-fa0aeda065d9.png)
Some iPhones 'user Agent' info is too long to fit in the DB. Prolonge lenghth of DB or shorten the string when putting into DB is needed

**Comment by tobias-kuendig** [comment]
Thank you! This is fixed in 8f0da7d
