### ISSUE TITLE
Restructuring of backend fields

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-gdpr-plugin#9]
### List

* [X] Name -> Name/Owner (078aeda)

### Form

* [x] Description Field (6fbe344)

* Rename to Purpose
* Comment: Describe the Purpose of the Use, Processing and any Notifications e.g. Determines if the user's navigation should be registered in a certain statistical placeholder
* Make required
* Make larger

### Form

* [x] New field `Name (Cookie Identification)` (2713800)
* Comment: The Name of the of the Cookie Prefix code e.g. _ga, ASP.NET_SessionId
* Required: No (Not everything will use a cookie code - like social sharing buttons)
* Field Type: Taglist

* [x] New field `Provider` (2713800)

* Comment: Under ePrivacy Law, you need to state the website domain name e.g. google.com
* Required: Yes (has to be displayed by law)
* Field Type = String

* [X] Rename Cookie Levels to `Manage Levels` (202177a)
* [X] Rename description field to purpose (6fbe344)
* [X] Make Purpose field required (6fbe344)

* [x] Add field Duration/Expiry (2713800)

* Comment: Under ePrivacy Law, you need to state how long it will be used in the user browser e.g. Session, 3 months, 2 years.
* Required: Yes (has to be displayed by law)
* Field Type: String

* [x] Add field Type (2713800)

* Comment: Under ePrivacy Law, you need to state what type of cookie or module this is e.g. HTTP Cookie, Pixel Tracker, Twitter Widget
* Required: Yes (has to be displayed by law)
* Field Type:  String or Drop-Down Selector

* [X] Add field Contact Details of Data Controller (1922c55)

* Comment: Under ePrivacy Law, you have to give the DPO Contact Address of the cookie e.g. Cloudflare, Inc. 101 Townsend St. San Francisco, CA 94107. Attention: Data Protection Officer, privacyquestions@cloudflare.com
* Required: Yes (has to be displayed by law)
* Field Type: TextArea

* [X] Add field Contact DPO (1922c55)

* Comment: Under ePrivacy Law, you need to give a link directly to the webpage of the DPO of the cookie e.g. Link to their Terms, Privacy, Cookie Privacy page etc.
* Required: Yes (has to be displayed by law)
* Field Type: String or repeater field (link & anchor)

![](https://user-images.githubusercontent.com/17784082/41507564-729064e2-722c-11e8-9a56-a3ece29dff7d.png)

* [X] Move Group Description field from own tab to base form layout (013ea5b)

![](https://user-images.githubusercontent.com/17784082/41507058-344d783c-7222-11e8-9896-53fa07e14997.png)

via https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/issues/8

**Comment by ayumihamsaki** [comment]
Thinking it would be easier to make a repeater field and have these items under the "Manage Levels".

For example:

## Top Level:

- Name/Owner
- Purpose
- Contact Details of DPO
- Contact DPO

## Manage Levels

- Name (Cookie Identification)
- Provider
- Duration/Expiry
- Type

**Note:** You will always have at _least two levels for everything_ being **on** and **off**.

**Comment by ayumihamsaki** [comment]
~Just to let you know I am currently working on a list for:

`Cookie Groups > Form > Purpose`

Should be done this week.  Looks like this so far:

![untitled](https://user-images.githubusercontent.com/17784082/41622476-974a6daa-7407-11e8-8408-76ad990aa3b4.png)

 Hopefully gives you idea,..

**Comment by tobias-kuendig** [comment]
The first batch of changes to the backend is done and can be previewed on our demo installation:

https://mall.offline.swiss/backend/offline/gdpr/cookiegroups/update/1

Feedback is as always welcome!

**Comment by ayumihamsaki** [comment]
@tobias-kuendig 

> Add field Type (2713800)

Had a think on this and made a list for users to select, to save them time:

- API
- Authentication cookie
- Browser sniffing
- Canvas fingerprinting
- Content sniffing
- Device fingerprint
- Email web beacon
- Embeds
- ETag
- Evercookie
- Facebook Beacon
- Hidden form field
- HTTP authentication
- HTTP cookie
- Identifier for advertisers
- Iframes
- Indexed Database API (IndexedDB)
- IP address
- JSON Web Token (JWT)
- Local shared objects (Flash cookies)
- localStorage
- Persistent cookie
- Push notification
- Session cookie
- sessionStorage
- Social bookmarking
- Social share
- Supercookie
- Third-party cookie
- Timelines
- Tracking cookie
- URL (query string)
- Web annotation
- Web beacon (Tracking Pixel)
- Web SQL Database
- Web storage (DOM storage)
- Widgets
- Zombie cookie

**Comment by ayumihamsaki** [comment]
> The first batch of changes to the backend is done and can be previewed on our demo installation:
> 
> https://mall.offline.swiss/backend/offline/gdpr/cookiegroups/update/1
> 
> Feedback is as always welcome!

Hi I find it hard to read, gonna do a Pull Request for you!

**Comment by ayumihamsaki** [comment]
Thinking of updating the Cookie Group screen to this, when I finish putting together the list of Purpose Desciptions for a bunch of cookies, see screenshot of idea:

![untitled](https://user-images.githubusercontent.com/17784082/41662348-ce3fed44-7498-11e8-88a5-0b94331ef07c.png)

**Comment by ayumihamsaki** [comment]
@tobias-kuendig Can close this if you want. I think its done now.
