### ISSUE TITLE
Cookie Manager: Text is not escaped

### ISSUE THREAD

**Issue by ogalbnafets** [OFFLINE-GmbH/oc-gdpr-plugin#93]
![Bildschirmfoto 2022-07-31 um 01 14 07](https://user-images.githubusercontent.com/70335936/182003212-afb02a82-c8bb-476b-b535-e709f47aba0e.png)
Hello!

I got the plugin running but I have a problem: the text (names, descriptions) are not correctly displayed as shown in the screenshot.
Did I miss something? Can you help?

Thanks!

**Comment by tobias-kuendig** [comment]
Can you try and remove the `html_clean` calls in `plugins/offline/gdpr/components/cookiemanager/cookie.htm` and see if it changes the output?

```twig
{{ html_clean(cookie.description | raw) }}
```

becomes

```twig
{{ cookie.description | raw }}
```

Refs #83

**Comment by ogalbnafets** [comment]
Thanks, this works!

Running OCMS 2.2.32
